# Generated by Django 3.2.9 on 2021-11-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sectors', to='Resto.district'),
        ),
    ]
